let suggestions = [
    "Main city",
    "Other cities",
    "Fallen gods area",
    "Edron bossrun area",
    "Kingdom Farmlands",
    "Yalahar abysses of achernar",
    "Set upgrades",
    "Weapon and shield upgrades",
    "Access quests",
    "Vroengaard",
    "Wild warrior cave",
    "World teleport",
    "Aberon",
    "Adicama",
    "Drushak",
    "Edron/qutor's grove",
    "Forbidden forest",
    "Fendal",
    "Lithgow",
    "Snowmania",
    "Tarid",
    "Valmoor",
    "Plains of gold",
    "Mysticon",
    "Wrecked ship",
    "Skyrider waterfalls",
    "Spaceship key",
    "Beluna",
    "Desert of zenith",
    "Yalahar",
    "Yalahar cirlces",
    "Yalahar spaceship",
    "Kingdom farmlands part 1",
    "Kingdom farmlands part 2",
    "Kingdom farmlands part 3",
    "Yalahar abysses of achernar part 1",
    "Yalahar abysses of achernar part 2",
    "Yalahar abysses of achernar part 3",
    "Spacewalk",
    "Achernar's prison",
    "Dark warrior set",
    "Zenith set to draconian set",
    "Draconia set to Fallen gods set",
    "Fallen gods set to Helarctos set",
    "Helarctos set to Dark overlord set",
    "Dark overlord set to Cyclip set",
    "Cyclip set to Craak slayer set",
    "Full hota quest",
    "Oceanic lizard weapon to skyrider weapon",
    "Cyclip shield quest",
    "Oceanic lizard shield quest",
    "Skyrider shield quest",
]