const pages = [
   {title: "Main city", url: "maincity.html"},
   {title: "Other cities", url: ""},
   {title: "Fallen gods area", url: ""},
   {title: "Edron bossrun area", url: ""},
   {title: "Kingdom Farmlands", url: ""},
   {title: "Yalahar abysses of achernar", url: ""},
   {title: "Set upgrades", url: ""},
   {title: "Weapon and shield upgrades", url: ""},
   {title: "Access quests", url: ""},
   {title: "Vroengaard", url: "cities/Vroengaard.html"},
   {title: "Wild warrior cave", url: "cities/Wildwarriorcave.html"},
   {title: "World teleport", url: "cities/worldteleport.html"},
   {title: "Aberon", url: ""},
   {title: "Adicama", url: ""},
   {title: "Drushak", url: ""},
   {title: "Edron/qutor's grove", url: ""},
   {title: "Forbidden forest", url: ""},
   {title: "Fendal", url: ""},
   {title: "Lithgow", url: ""},
   {title: "Snowmania", url: ""},
   {title: "Tarid", url: ""},
   {title: "Valmoor", url: ""},
   {title: "Plains of gold", url: ""},
   {title: "Mysticon", url: ""},
   {title: "Wrecked ship", url: ""},
   {title: "Skyrider waterfalls", url: ""},
   {title: "Spaceship key", url: ""},
   {title: "Beluna", url: ""},
   {title: "Desert of zenith", url: ""},
   {title: "Yalahar", url: ""},
   {title: "Yalahar cirlces", url: ""},
   {title: "Yalahar spaceship", url: ""},
   {title: "Kingdom farmlands part 1", url: ""},
   {title: "Kingdom farmlands part 2", url: ""},
   {title: "Kingdom farmlands part 3", url: ""},
   {title: "Yalahar abysses of achernar part 1", url: ""},
   {title: "Yalahar abysses of achernar part 2", url: ""},
   {title: "Yalahar abysses of achernar part 3", url: ""},
   {title: "Spacewalk", url: ""},
   {title: "Achernar's prison", url: ""},
   {title: "Dark warrior set", url: ""},
   {title: "Zenith set to draconian set", url: ""},
   {title: "Draconia set to Fallen gods set", url: ""},
   {title: "Fallen gods set to Helarctos set", url: ""},
   {title: "Helarctos set to Dark overlord set", url: ""},
   {title: "Dark overlord set to Cyclip set", url: ""},
   {title: "Cyclip set to Craak slayer set", url: ""},
   {title: "Full hota quest", url: ""},
   {title: "Oceanic lizard weapon to skyrider weapon", url: ""},
   {title: "Cyclip shield quest", url: ""},
   {title: "Oceanic lizard shield quest", url: ""},
   {title: "Skyrider shield quest", url: ""}
]